name: Test

on:
  schedule:
    - cron:  '1 0 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java-version: [17]
        java-distribution: ["corretto"]
        python-version: ["3.8", "3.11"]
    env:
      PIP_ONLY_BINARY: cmake,numpy,pandas
      PIP_PRE: "1"

    name: test (${{ matrix.os }}) - Python ${{ matrix.python-version }}, JDK${{ matrix.java-version }}

    steps:
    - name: 'Python ${{ matrix.python-version }}' (MacOS and Windows)
      if: matrix.os != 'ubuntu-latest'
      uses: actions/setup-python@v4
      with:
        python-version: '${{ matrix.python-version }}'
        architecture: 'x86'
        allow-prereleases: true

    - name: Set up Conda with Python and ROOT (Linux only)
      if: matrix.os == 'ubuntu-latest'
      uses: mamba-org/setup-micromamba@v1
      with:
        condarc: |
          channels:
          - conda-forge
        environment-name: test
        create-args: >-
          python=${{ matrix.python-version }}
          numpy
          root

    - name: Set up JDK ${{ matrix.java-distribution }}/${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: ${{ matrix.java-distribution }}

    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        python -m pip install xgboost
        python -m pip install tritonclient[grpc,http]
        python -m pip list
        java -version

    - name: Install dependencies (MacOS)
      if: matrix.os == 'macOS-latest'
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        python -m pip install xgboost
        python -m pip list
        java -version

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        python -m pip install xgboost
        python -m pip list
        java -version

    - name: Check out scikit-hep/awkward
      uses: actions/checkout@v4
      with:
        repository: scikit-hep/awkward
        path: awkward
        submodules: true

    - name: Check out dask-contrib/dask-awkward
      uses: actions/checkout@v4
      with:
        repository: dask-contrib/dask-awkward
        path: dask-awkward

    - name: Check out scikit-hep/uproot5
      uses: actions/checkout@v4
      with:
        repository: scikit-hep/uproot5
        path: uproot5

    - name: Check out CoffeaTeam/coffea
      uses: actions/checkout@v4
      with:
        repository: CoffeaTeam/coffea
        path: coffea

    - name: See what we've got
      run: pwd ; ls -R
