name: CI/CD

on:
  schedule:
    - cron:  '1 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java-version: [17]
        java-distribution: ["corretto"]
        python-version: ["3.8", "3.11"]
        architecture: ["x64"]
    env:
      PIP_ONLY_BINARY: cmake,numpy,pandas
      PIP_PRE: "1"

    name: test (${{ matrix.os }}, ${{ matrix.architectur }}) - Python ${{ matrix.python-version }}, JDK${{ matrix.java-version }}

    steps:
    - name: 'Python ${{ matrix.python-version }}'
      uses: actions/setup-python@v4
      with:
        python-version: '${{ matrix.python-version }}'
        architecture: '${{ matrix.architecture }}'
        allow-prereleases: true

    - name: Set up JDK ${{ matrix.java-distribution }}/${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: ${{ matrix.java-distribution }}

    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        python -m pip install xgboost
        python -m pip install tritonclient[grpc,http]
        python -m pip install -q -e '.[dev,parsl,dask,spark]' --upgrade --upgrade-strategy eager
        python -m pip list
        java -version

    - name: Install dependencies (MacOS)
      if: matrix.os == 'macOS-latest'
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        python -m pip install xgboost
        python -m pip install -q -e '.[dev,dask,spark]' --upgrade --upgrade-strategy eager
        python -m pip list
        java -version

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        python -m pip install xgboost
        python -m pip install -q -e '.[dev,dask]' --upgrade --upgrade-strategy eager
        python -m pip list
        java -version

    - name: Check out my other private repo
      uses: actions/checkout@master
      with:
        repository: scikit-hep/awkward

    - name: Check out my other private repo
      uses: actions/checkout@master
      with:
        repository: dask-contrib/dask-awkward

    - name: Check out my other private repo
      uses: actions/checkout@master
      with:
        repository: scikit-hep/uproot5

    - name: Check out my other private repo
      uses: actions/checkout@master
      with:
        repository: CoffeaTeam/coffea

    - name: See what we've got
      run: pwd ; ls -R
